# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_colorRust_wrappers", use_symbols = TRUE, package_name = "colorRust")

#' @docType package
#' @usage NULL
#' @useDynLib colorRust, .registration = TRUE
NULL

#' rust_cast：用Rust實踐cat命令
#'
#' 選擇以不同的方式顯示文件的內容
#'
#' @param file_name 文件名
#' @param number_lines 是否顯示行號
#' @param number_nonblank_lines 是否顯示非空行號
#'
#' @examples
#' rust_cat("colorRust-Ex.R", TRUE, FALSE)
#'@export
rust_cat <- function(file_name, number_lines, number_nonblank_lines) invisible(.Call(wrap__rust_cat, file_name, number_lines, number_nonblank_lines))


# nolint end
