# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_colorRust_wrappers", use_symbols = TRUE, package_name = "colorRust")

#' @docType package
#' @usage NULL
#' @useDynLib colorRust, .registration = TRUE
NULL

#' rust_cast：用Rust實踐cat命令
#'
#' 選擇以不同的方式顯示文件的內容
#'
#' @param file_name 文件名
#' @param number_lines 是否顯示行號
#' @param number_nonblank_lines 是否顯示非空行號
#'
#' @examples
#' rust_cat("colorRust-Ex.R", TRUE, FALSE)
#'@export
rust_cat <- function(file_name, number_lines, number_nonblank_lines) invisible(.Call(wrap__rust_cat, file_name, number_lines, number_nonblank_lines))

#' rust_head：用Rust實踐head命令
#'
#' 檢視檔案前幾行、前幾位元，也可以檢視多個文件
#'
#' @param file 可以是某個根目錄或指定文件
#' @param type_file 文件類型，如txt,csv...，預設是不指定
#' @param n 印出幾行內容，預設10
#' @param byte 印出幾個字元，預設是0(0是全部的意思)
#'
#' @examples
#' rust_head("colorRust-Ex.R", "", 10, 0)
#'@export
rust_head <- function(file, type_file, n, byte) invisible(.Call(wrap__rust_head, file, type_file, n, byte))


# nolint end
